<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="student-virtual-machine" name="Command line test" tests="60" failures="10" timestamp="21 May 2015 00:12:38 GMT" time="17.465" errors="0">
  <testcase name="testCreate" time="0.227" classname="ReviewAndInformation.Respository.GoToPlacesRepoTest"/>
  <testcase name="testCreate" time="0.021" classname="ReviewAndInformation.Services.GoToPlacesServiceTest"/>
  <testcase name="testCreate" time="0.019" classname="ReviewAndInformation.Respository.cityInfoRepoTest"/>
  <testcase name="testCreate" time="0.055" classname="ReviewAndInformation.Services.cityInfoServiceTest"/>
  <testcase name="testCreate" time="0.009" classname="ReviewAndInformation.Respository.dangerPlacesRepoTest"/>
  <testcase name="testCreate" time="0.011" classname="ReviewAndInformation.Services.dangerPlacesServiceTest"/>
  <testcase name="testCreate" time="0.014" classname="ReviewAndInformation.Respository.directorRepoTest"/>
  <testcase name="testCreate" time="0.02" classname="ReviewAndInformation.Services.directorServiceTest"/>
  <testcase name="testCreate" time="0.078" classname="ReviewAndInformation.Respository.movieRepoTest"/>
  <testcase name="testCreate" time="0.306" classname="ReviewAndInformation.Services.movieServiceTest">
    <failure type="org.springframework.dao.DataIntegrityViolationException" message="could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement">
      <![CDATA[org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:255)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:221)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:417)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy72.save(Unknown Source)
	at ReviewAndInformation.Services.movieServiceTest.testCreate(movieServiceTest.java:35)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:72)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3558)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:98)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:492)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:197)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:181)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:216)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:291)
	at com.sun.proxy.$Proxy60.persist(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:407)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:416)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:401)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:373)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	... 45 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '84' for key 'UK_ok7xex41a4p0dr5unwpmdrbeu'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 86 more
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- testCreate -->
  <testcase name="testCreate" time="0.072" classname="ReviewAndInformation.Respository.musicTypeRepoTest"/>
  <testcase name="testCreate" time="0.022" classname="ReviewAndInformation.Services.musicTypeServiceTest"/>
  <testcase name="testCreate" time="0.011" classname="ReviewAndInformation.Respository.placeMovieSetRepoTest"/>
  <testcase name="testCreate" time="0.053" classname="ReviewAndInformation.Services.placeMovieSetServiceTest"/>
  <testcase name="testCreate" time="0.169" classname="ReviewAndInformation.Respository.producerRepoTest"/>
  <testcase name="testCreate" time="0.021" classname="ReviewAndInformation.Services.producerServiceTest"/>
  <testcase name="testCreate" time="0.03" classname="ReviewAndInformation.Respository.recordLabelRepoTest"/>
  <testcase name="testCreate" time="0.122" classname="ReviewAndInformation.Services.recordLabelServiceTest"/>
  <testcase name="testCreate" time="0.054" classname="ReviewAndInformation.Respository.singerRepoTest"/>
  <testcase name="testCreate" time="0.041" classname="ReviewAndInformation.Services.singerServiceTest"/>
  <testcase name="testRead" time="0.107" classname="ReviewAndInformation.Respository.GoToPlacesRepoTest"/>
  <testcase name="testGetCityInfo" time="0.5" classname="ReviewAndInformation.Services.GoToPlacesServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.GoToPlacesServiceTest.testGetCityInfo(GoToPlacesServiceTest.java:42)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.004" classname="ReviewAndInformation.Respository.cityInfoRepoTest"/>
  <testcase name="testGetCityInfo" time="0.01" classname="ReviewAndInformation.Services.cityInfoServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.cityInfoServiceTest.testGetCityInfo(cityInfoServiceTest.java:50)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.005" classname="ReviewAndInformation.Respository.dangerPlacesRepoTest"/>
  <testcase name="testGetCityInfo" time="0.012" classname="ReviewAndInformation.Services.dangerPlacesServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.dangerPlacesServiceTest.testGetCityInfo(dangerPlacesServiceTest.java:50)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.006" classname="ReviewAndInformation.Respository.directorRepoTest"/>
  <testcase name="testGetCityInfo" time="0.013" classname="ReviewAndInformation.Services.directorServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.directorServiceTest.testGetCityInfo(directorServiceTest.java:44)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.006" classname="ReviewAndInformation.Respository.movieRepoTest"/>
  <testcase name="testGetCityInfo" time="0.0" classname="ReviewAndInformation.Services.movieServiceTest">
    <skipped/>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.005" classname="ReviewAndInformation.Respository.musicTypeRepoTest"/>
  <testcase name="testGetCityInfo" time="0.01" classname="ReviewAndInformation.Services.musicTypeServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.musicTypeServiceTest.testGetCityInfo(musicTypeServiceTest.java:42)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.005" classname="ReviewAndInformation.Respository.placeMovieSetRepoTest"/>
  <testcase name="testGetCityInfo" time="0.008" classname="ReviewAndInformation.Services.placeMovieSetServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.placeMovieSetServiceTest.testGetCityInfo(placeMovieSetServiceTest.java:42)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.006" classname="ReviewAndInformation.Respository.producerRepoTest"/>
  <testcase name="testGetCityInfo" time="0.009" classname="ReviewAndInformation.Services.producerServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.producerServiceTest.testGetCityInfo(producerServiceTest.java:44)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.007" classname="ReviewAndInformation.Respository.recordLabelRepoTest"/>
  <testcase name="testGetCityInfo" time="0.017" classname="ReviewAndInformation.Services.recordLabelServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.recordLabelServiceTest.testGetCityInfo(recordLabelServiceTest.java:42)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testRead" time="0.005" classname="ReviewAndInformation.Respository.singerRepoTest"/>
  <testcase name="testGetCityInfo" time="0.015" classname="ReviewAndInformation.Services.singerServiceTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at ReviewAndInformation.Services.singerServiceTest.testGetCityInfo(singerServiceTest.java:42)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetCityInfo -->
  <testcase name="testUpdate" time="0.155" classname="ReviewAndInformation.Respository.GoToPlacesRepoTest"/>
  <testcase name="testUpdate" time="0.025" classname="ReviewAndInformation.Respository.cityInfoRepoTest"/>
  <testcase name="testUpdate" time="0.018" classname="ReviewAndInformation.Respository.dangerPlacesRepoTest"/>
  <testcase name="testUpdate" time="0.022" classname="ReviewAndInformation.Respository.directorRepoTest"/>
  <testcase name="testUpdate" time="0.056" classname="ReviewAndInformation.Respository.movieRepoTest"/>
  <testcase name="testUpdate" time="0.015" classname="ReviewAndInformation.Respository.musicTypeRepoTest"/>
  <testcase name="testUpdate" time="0.015" classname="ReviewAndInformation.Respository.placeMovieSetRepoTest"/>
  <testcase name="testUpdate" time="0.017" classname="ReviewAndInformation.Respository.producerRepoTest"/>
  <testcase name="testUpdate" time="0.013" classname="ReviewAndInformation.Respository.recordLabelRepoTest"/>
  <testcase name="testUpdate" time="0.02" classname="ReviewAndInformation.Respository.singerRepoTest"/>
  <testcase name="testDelete" time="0.044" classname="ReviewAndInformation.Respository.GoToPlacesRepoTest"/>
  <testcase name="testDelete" time="0.02" classname="ReviewAndInformation.Respository.cityInfoRepoTest"/>
  <testcase name="testDelete" time="0.023" classname="ReviewAndInformation.Respository.dangerPlacesRepoTest"/>
  <testcase name="testDelete" time="0.018" classname="ReviewAndInformation.Respository.directorRepoTest"/>
  <testcase name="testDelete" time="0.023" classname="ReviewAndInformation.Respository.movieRepoTest"/>
  <testcase name="testDelete" time="0.025" classname="ReviewAndInformation.Respository.musicTypeRepoTest"/>
  <testcase name="testDelete" time="0.019" classname="ReviewAndInformation.Respository.placeMovieSetRepoTest"/>
  <testcase name="testDelete" time="0.019" classname="ReviewAndInformation.Respository.producerRepoTest"/>
  <testcase name="testDelete" time="0.018" classname="ReviewAndInformation.Respository.recordLabelRepoTest"/>
  <testcase name="testDelete" time="0.019" classname="ReviewAndInformation.Respository.singerRepoTest"/>
</testsuite> <!-- Command line test -->
